version: "3"
services:
  raincloud:
    image: jpjodoin/raincloud
    container_name: raincloud
    ports:
      - "80:80"
    restart: always
    environment:
      - MELNOR_DEVICEID=D01234AB01D0 # TODO: Replace me
    #volumes:
    #  - TODO Logs
    #read_only: true
    tmpfs:
      - /root
     # - /opt/rel/releases